name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        node: [ 14 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install core dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Pack
        run: yarn prepack

      # Playground Dependencies
      - name: Install nuxt-bridge dependencies
        run: cd packages/playground/nuxt-bridge && yarn install

      - name: Install nuxt2-vite dependencies
        run: cd packages/playground/nuxt2-vite && yarn install

      - name: Install nuxt2-webpack dependencies
        run: cd packages/playground/nuxt2-webpack && yarn install

      - name: Install nuxt3-webpack dependencies
        run: cd packages/playground/nuxt3-webpack && yarn install

      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
