name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [  ubuntu-latest ]
        node: [ 14, 16 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install core dependencies
        run: pnpm install

      - name: Pack
        run: pnpm prepack

      # Playground Dependencies
      - name: Install nuxt-bridge dependencies
        run: cd packages/playground/nuxt-bridge && pnpm install

      - name: Install nuxt2-vite dependencies
        run: cd packages/playground/nuxt2-vite && pnpm install

      - name: Install nuxt2-webpack dependencies
        run: cd packages/playground/nuxt2-webpack && pnpm install

      - name: Install nuxt3-webpack dependencies
        run: cd packages/playground/nuxt3-webpack && pnpm install

      - name: Run linter
        run: pnpm lint
      - name: Run tests
        run: pnpm test
